import type { UniverseId } from "../types";

/**
 * Scan universe metadata. In production this list would be fetched from the
 * data provider; the shape is provider-agnostic. Prices/fundamentals are
 * generated by the active provider, keyed by these seeds.
 */
export interface UniverseEntry {
  symbol: string;
  name: string;
  sector: string;
  industry: string;
  universe: UniverseId;
  /** rough base price used to seed the simulator */
  basePrice: number;
  /** rough market cap in dollars, seeds fundamentals */
  baseCap: number;
  /** bias applied to the simulated regime: >0 leans bullish, <0 bearish */
  drift: number;
  summary: string;
}

const sp = (
  symbol: string, name: string, sector: string, industry: string,
  basePrice: number, capB: number, drift: number, summary: string,
): UniverseEntry => ({ symbol, name, sector, industry, universe: "sp500", basePrice, baseCap: capB * 1e9, drift, summary });

const rt = (
  symbol: string, name: string, sector: string, industry: string,
  basePrice: number, capB: number, drift: number, summary: string,
): UniverseEntry => ({ symbol, name, sector, industry, universe: "russell2000", basePrice, baseCap: capB * 1e9, drift, summary });

export const UNIVERSE: UniverseEntry[] = [
  // ---- S&P 500 representatives ----
  sp("AAPL", "Apple Inc.", "Technology", "Consumer Electronics", 228, 3450, 0.4, "Designs and sells iPhone, Mac, iPad, wearables and a growing services business spanning the App Store, iCloud and payments."),
  sp("MSFT", "Microsoft Corp.", "Technology", "Software — Infrastructure", 452, 3350, 0.7, "Builds Windows, Office 365 and the Azure cloud platform, with major investments in AI infrastructure and enterprise software."),
  sp("NVDA", "NVIDIA Corp.", "Technology", "Semiconductors", 138, 3400, 1.1, "Designs GPUs and AI accelerator chips that power gaming, data centers and most modern AI training and inference."),
  sp("AMZN", "Amazon.com Inc.", "Consumer Cyclical", "Internet Retail", 218, 2280, 0.6, "Runs the world's largest online marketplace plus AWS, the leading cloud-computing platform, along with advertising and logistics arms."),
  sp("GOOGL", "Alphabet Inc.", "Communication Services", "Internet Content", 182, 2250, 0.5, "Parent of Google Search, YouTube, Android and Google Cloud; earns most revenue from digital advertising."),
  sp("META", "Meta Platforms Inc.", "Communication Services", "Internet Content", 655, 1650, 0.8, "Operates Facebook, Instagram, WhatsApp and Threads, monetized primarily through targeted advertising, with heavy AI and VR investment."),
  sp("TSLA", "Tesla Inc.", "Consumer Cyclical", "Auto Manufacturers", 310, 990, -0.2, "Makes electric vehicles and energy storage products and is developing autonomous driving software and robotics."),
  sp("AVGO", "Broadcom Inc.", "Technology", "Semiconductors", 172, 800, 0.9, "Supplies networking, broadband and custom AI chips, plus infrastructure software after the VMware acquisition."),
  sp("BRK.B", "Berkshire Hathaway", "Financial Services", "Insurance — Diversified", 462, 1000, 0.3, "Warren Buffett's conglomerate holding insurance, railroads, energy, and large public-equity stakes."),
  sp("JPM", "JPMorgan Chase & Co.", "Financial Services", "Banks — Diversified", 245, 690, 0.5, "The largest U.S. bank by assets, spanning consumer banking, investment banking, and asset management."),
  sp("LLY", "Eli Lilly and Co.", "Healthcare", "Drug Manufacturers", 780, 740, 0.6, "Pharmaceutical giant behind fast-growing GLP-1 weight-loss and diabetes treatments plus oncology and immunology drugs."),
  sp("V", "Visa Inc.", "Financial Services", "Credit Services", 315, 640, 0.5, "Runs the world's largest card-payment network, earning fees on trillions of dollars of transactions."),
  sp("UNH", "UnitedHealth Group", "Healthcare", "Healthcare Plans", 520, 480, -0.4, "The largest U.S. health insurer, paired with the Optum health-services and pharmacy-benefits arm."),
  sp("XOM", "Exxon Mobil Corp.", "Energy", "Oil & Gas Integrated", 118, 520, 0.1, "Integrated oil and gas major producing, refining and selling energy products worldwide."),
  sp("MA", "Mastercard Inc.", "Financial Services", "Credit Services", 528, 490, 0.5, "Global payments network competing with Visa, plus a growing services and fraud-analytics business."),
  sp("HD", "Home Depot Inc.", "Consumer Cyclical", "Home Improvement Retail", 415, 410, 0.2, "The largest home-improvement retailer, serving both do-it-yourself customers and professional contractors."),
  sp("PG", "Procter & Gamble", "Consumer Defensive", "Household Products", 172, 405, 0.1, "Consumer-staples giant behind Tide, Pampers, Gillette and dozens of household brands."),
  sp("COST", "Costco Wholesale", "Consumer Defensive", "Discount Stores", 985, 435, 0.6, "Membership warehouse retailer known for loyal customers, low margins and steady comparable-sales growth."),
  sp("JNJ", "Johnson & Johnson", "Healthcare", "Drug Manufacturers", 152, 365, 0.0, "Diversified healthcare company focused on pharmaceuticals and medical devices after spinning off its consumer arm."),
  sp("ABBV", "AbbVie Inc.", "Healthcare", "Drug Manufacturers", 196, 345, 0.4, "Pharma company behind immunology blockbusters Skyrizi and Rinvoq, transitioning from the Humira patent cliff."),
  sp("CRM", "Salesforce Inc.", "Technology", "Software — Application", 275, 265, 0.2, "The leading customer-relationship-management (CRM) software platform, expanding into data and AI agents."),
  sp("NFLX", "Netflix Inc.", "Communication Services", "Entertainment", 1020, 435, 0.8, "The largest subscription streaming service, now with an advertising tier and live-event ambitions."),
  sp("AMD", "Advanced Micro Devices", "Technology", "Semiconductors", 126, 205, 0.3, "Designs CPUs and GPUs competing with Intel and NVIDIA across PCs, servers and AI accelerators."),
  sp("KO", "Coca-Cola Co.", "Consumer Defensive", "Beverages", 68, 295, 0.2, "Global beverage company with the world's most recognized soft-drink brand and a large dividend history."),
  sp("PEP", "PepsiCo Inc.", "Consumer Defensive", "Beverages", 152, 210, -0.1, "Snacks-and-beverages giant behind Pepsi, Gatorade, Lay's and Quaker."),
  sp("WMT", "Walmart Inc.", "Consumer Defensive", "Discount Stores", 96, 770, 0.7, "The world's largest retailer, growing quickly in e-commerce, advertising, and grocery delivery."),
  sp("DIS", "Walt Disney Co.", "Communication Services", "Entertainment", 112, 205, 0.1, "Entertainment conglomerate spanning theme parks, film studios, ESPN and the Disney+ streaming service."),
  sp("CAT", "Caterpillar Inc.", "Industrials", "Farm & Heavy Machinery", 385, 185, 0.4, "Makes construction and mining equipment, engines and locomotives sold worldwide."),
  sp("GE", "GE Aerospace", "Industrials", "Aerospace & Defense", 205, 220, 0.7, "Builds and services jet engines for commercial and military aircraft after GE's three-way split."),
  sp("BA", "Boeing Co.", "Industrials", "Aerospace & Defense", 178, 135, -0.5, "One of two global large-aircraft makers, working through production-quality and certification challenges."),
  sp("GS", "Goldman Sachs Group", "Financial Services", "Capital Markets", 590, 185, 0.6, "Leading investment bank in trading, dealmaking and asset management."),
  sp("PFE", "Pfizer Inc.", "Healthcare", "Drug Manufacturers", 27, 152, -0.3, "Large pharma with a broad portfolio, working to replace declining COVID-era revenue with oncology bets."),
  sp("INTC", "Intel Corp.", "Technology", "Semiconductors", 22, 96, -0.6, "Historic chipmaker attempting a turnaround built on new manufacturing processes and a foundry business."),
  sp("ORCL", "Oracle Corp.", "Technology", "Software — Infrastructure", 178, 495, 0.8, "Database and enterprise-software company with a fast-growing cloud infrastructure arm fueled by AI demand."),
  sp("CVX", "Chevron Corp.", "Energy", "Oil & Gas Integrated", 152, 270, 0.1, "Integrated energy major with global upstream production and U.S. refining."),
  sp("MRK", "Merck & Co.", "Healthcare", "Drug Manufacturers", 98, 248, -0.2, "Pharma company anchored by the blockbuster cancer immunotherapy Keytruda."),
  sp("ADBE", "Adobe Inc.", "Technology", "Software — Application", 465, 205, -0.1, "Creative-software leader (Photoshop, Premiere) adding generative-AI features across its suite."),
  sp("MCD", "McDonald's Corp.", "Consumer Cyclical", "Restaurants", 295, 212, 0.2, "The world's largest fast-food chain, run mostly through franchisees with heavy digital investment."),
  sp("NKE", "Nike Inc.", "Consumer Cyclical", "Footwear & Accessories", 76, 115, -0.4, "Global athletic footwear and apparel brand working to reignite growth and wholesale relationships."),
  sp("UBER", "Uber Technologies", "Technology", "Software — Application", 82, 172, 0.5, "Ride-hailing and delivery platform generating growing free cash flow from its global network."),
  // ---- Russell 2000 representatives (small caps) ----
  rt("CVNA", "Carvana Co.", "Consumer Cyclical", "Auto & Truck Dealerships", 245, 42, 0.9, "Online used-car retailer known for car vending machines and a dramatic balance-sheet turnaround."),
  rt("SMCI", "Super Micro Computer", "Technology", "Computer Hardware", 42, 25, 0.4, "Builds AI-optimized servers and rack systems, riding data-center buildouts."),
  rt("IONQ", "IonQ Inc.", "Technology", "Quantum Computing", 34, 7, 0.6, "Develops trapped-ion quantum computers sold through major cloud platforms."),
  rt("RKLB", "Rocket Lab USA", "Industrials", "Aerospace & Defense", 24, 12, 0.8, "Launches small satellites with its Electron rocket and is developing the larger Neutron vehicle."),
  rt("ACLS", "Axcelis Technologies", "Technology", "Semiconductor Equipment", 78, 2.5, -0.2, "Makes ion-implantation equipment used in chip manufacturing, exposed to the power-semiconductor cycle."),
  rt("CROX", "Crocs Inc.", "Consumer Cyclical", "Footwear & Accessories", 108, 6.5, 0.1, "Casual-footwear maker behind the Crocs clog and HEYDUDE brands, generating strong cash flow."),
  rt("ELF", "e.l.f. Beauty", "Consumer Defensive", "Household & Personal Products", 128, 7.2, 0.5, "Fast-growing budget cosmetics brand taking share with viral marketing and quick product cycles."),
  rt("DUOL", "Duolingo Inc.", "Technology", "Software — Application", 345, 15, 0.7, "Gamified language-learning app monetized by subscriptions, expanding into math and music."),
  rt("HIMS", "Hims & Hers Health", "Healthcare", "Health Information Services", 42, 9, 0.9, "Telehealth platform selling subscription treatments across dermatology, mental health and weight loss."),
  rt("APP", "AppLovin (grad.)", "Technology", "Software — Application", 320, 108, 1.0, "Ad-tech platform whose AI engine matches mobile ads to users; a recent small-cap graduate."),
  rt("KTOS", "Kratos Defense", "Industrials", "Aerospace & Defense", 32, 4.8, 0.6, "Builds military drones, hypersonic test vehicles and defense electronics."),
  rt("ANF", "Abercrombie & Fitch", "Consumer Cyclical", "Apparel Retail", 145, 7.4, 0.3, "Reinvented apparel retailer posting strong comparable-sales growth across its namesake and Hollister brands."),
  rt("MARA", "MARA Holdings", "Financial Services", "Capital Markets", 19, 6.3, -0.3, "One of the largest bitcoin miners, with results tied closely to bitcoin's price and network economics."),
  rt("SFIX", "Stitch Fix Inc.", "Consumer Cyclical", "Internet Retail", 4.6, 0.55, -0.5, "Online personal-styling service working through a multi-year turnaround."),
  rt("PLAY", "Dave & Buster's", "Consumer Cyclical", "Restaurants", 34, 1.3, -0.4, "Operates eat-and-play entertainment venues combining arcades, sports bars and dining."),
  rt("TMDX", "TransMedics Group", "Healthcare", "Medical Devices", 92, 3.1, 0.5, "Makes organ-transport systems that keep donor organs functioning outside the body, plus an aviation logistics arm."),
  rt("CALM", "Cal-Maine Foods", "Consumer Defensive", "Farm Products", 95, 4.6, 0.4, "The largest U.S. producer of shell eggs, with earnings that swing on egg prices."),
  rt("INSW", "International Seaways", "Energy", "Oil & Gas Midstream", 48, 2.4, 0.2, "Operates a fleet of crude and product tankers, with profits tied to shipping day-rates."),
  rt("PRCT", "PROCEPT BioRobotics", "Healthcare", "Medical Devices", 78, 4.2, 0.6, "Sells a surgical robot for treating enlarged prostates, expanding hospital adoption."),
  rt("WULF", "TeraWulf Inc.", "Technology", "Data Infrastructure", 6.8, 2.6, 0.7, "Runs zero-carbon data centers pivoting from bitcoin mining toward AI compute hosting."),
];

export const SECTORS = Array.from(new Set(UNIVERSE.map((u) => u.sector))).sort();
export const INDUSTRIES = Array.from(new Set(UNIVERSE.map((u) => u.industry))).sort();

export function findEntry(symbol: string): UniverseEntry | undefined {
  return UNIVERSE.find((u) => u.symbol === symbol);
}
